### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by janoschbatschi** [richardhj/isotope-klarna-checkout#7]
Although the locale parameter for Klarna is set to "de-AT", the language in Isotope (tl_iso_product_collection) is set to "en" or left blank for external payment modules.

This leads to wrong translations in the confirmation mails.

**Comment by richardhj** [comment]
> Although the locale parameter for Klarna is set to "de-AT"

What locale parameter?

**Comment by janoschbatschi** [comment]
The one set for the KlarnaObjekt in KlarnaCheckout.php and therefore in the request-body (first image). 

Although Klarna does not support "de-AT" but "de-DE" it will fallback to "de-DE" (https://developers.klarna.com/documentation/klarna-checkout/in-depth/available-languages/)

But looking at the order-object before "save and complete order" in KlarnaCheckoutConfirmation.php", the language set is "en". (second image) 




![image](https://user-images.githubusercontent.com/2529951/98177228-76e04a80-1efa-11eb-9a19-c797d56eaddd.png)
![image](https://user-images.githubusercontent.com/2529951/98177147-3da7da80-1efa-11eb-820f-0b0f85b8f0ac.png)

**Comment by richardhj** [comment]
Can you check if the issue is fixed in version 1.0.3?

**Comment by richardhj** [comment]
Fixed in d4caa4b7a369abf8526fc7d8c09b92379e18cc4f.

Reference:
https://github.com/isotope/core/blob/c94eb8f67efed8d7606be817b525f958d3367efc/system/modules/isotope/library/Isotope/Model/ProductCollection.php#L689

**Comment by janoschbatschi** [comment]
Thank you Richard for the fast reply and the reference! This fixed the issue.

**Comment by janoschbatschi** [comment]
The fix works like a charm if the order is placed using Klarna. But for external payment methods (PayPal), it's still wrong because the language attribute is just empty. Therefore the default language English is used.
Do you have an idea of where to set the language attribute for external payment methods? (KlarnaCheckout.php?)

**Comment by richardhj** [comment]
For external payment methods, the order checkout happens inside the checkout module.
See https://github.com/richardhj/isotope-klarna-checkout/blob/c1c81094a8376a85a8a1328a3685209c115f6a44/src/Module/KlarnaCheckout.php#L363

This means the locale from the user request will be used. As we learned, the request locale will be used when saving the isotope order:
https://github.com/isotope/core/blob/c94eb8f67efed8d7606be817b525f958d3367efc/system/modules/isotope/library/Isotope/Model/ProductCollection.php#L689

I cannot tell, why the Isotope order locale fallbacks to English in this case.

**Comment by janoschbatschi** [comment]
I found a fix. Adding following line
`                $isotopeOrder->language = $GLOBALS['TL_LANGUAGE'];
`
in the "processExternalPaymentMethods()" method just before
https://github.com/richardhj/isotope-klarna-checkout/blob/c1c81094a8376a85a8a1328a3685209c115f6a44/src/Module/KlarnaCheckout.php#L411
fixed this issue.
